spring.application.name=IOT_service
server.port=8082

# DB (use container hostnames in Docker; use Azure DB host in Azure)
spring.datasource.url=${DATABASE_URL:jdbc:postgresql://smartcare-postgres.postgres.database.azure.com/sensordb}
spring.datasource.username=${DB_USERNAME:smartcarepgadmin}
spring.datasource.password=${DB_PASSWORD:admin@#123}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# Logging
logging.level.com.example.sensor=DEBUG
logging.level.org.springframework.web=INFO
logging.level.org.hibernate.SQL=DEBUG

# CORS (already handled in controller, but backup)
spring.web.cors.allowed-origins=*
spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
spring.web.cors.allowed-headers=*


# Kafka (IMPORTANT: docker -> kafka:9092, azure -> event hubs / kafka host)
#spring.kafka.bootstrap-servers=${KAFKA_BOOTSTRAP_SERVERS:kafka:9092}
#spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
#spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
#
#kafka.topic.sensor-data=${SENSOR_TOPIC:sensor-data-topic}
# Kafka - DISABLED (not used yet)
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

# Eureka registration
eureka.client.service-url.defaultZone=${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka}

# Actuator + Prometheus
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.show-details=always
management.metrics.tags.application=${spring.application.name}