#FROM maven:3.9-eclipse-temurin-17 AS build
#WORKDIR /app
#COPY . .
#RUN mvn -pl discoveryserver -am clean package -DskipTests


FROM eclipse-temurin:17-jre
WORKDIR /app
COPY discoveryserver/target/*.jar app.jar
EXPOSE 8761
ENTRYPOINT ["java","-jar","app.jar"]
